[project]
name = "admit-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DMen6L", email = "240103073@sdu.edu.kz" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
admit-hackathon = "admit_hackathon:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
